'use strict';
let plan=null;const el=id=>document.getElementById(id);
async function request(path,data){const r=await fetch('/api/agent/planner/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw Error(out.error);return out;}
function show(){el('tasks').replaceChildren();for(const t of plan.tasks){const card=document.createElement('article'),label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.value=t.task_id;check.disabled=['completed','pending_review'].includes(t.status);label.append(check,document.createTextNode(t.title+' · '+t.status));card.append(label);const info=document.createElement('pre');info.textContent='负责人：'+t.owner_ids.join('、')+'\n产物：'+t.deliverable+'\n验收：'+t.acceptance_criteria.join('；')+'\n步骤：'+t.steps.join(' → ')+'\n估时：'+t.estimate_minutes_range.join('–')+' 分钟\n前置：'+(t.depends_on.join('、')||'无')+'\n缺口：'+t.gap_ids.join('、');card.append(info);el('tasks').append(card);}el('result').textContent=JSON.stringify(plan,null,2);}
function handle(id,fn){el(id).onclick=async()=>{el(id).disabled=true;try{await fn();el('notice').textContent='草案已更新，请核对后导出给队长。';}catch(e){el('notice').textContent=e.message;}finally{el(id).disabled=false;}};}
handle('generate',async()=>{plan=await request('generate',{diagnosis:JSON.parse(el('diagnosis').value),context:{deadline:el('deadline').value||'待成员确认'}});show();});
handle('schedule',async()=>{if(!plan)throw Error('请先生成任务卡');const settings=JSON.parse(el('settings').value);settings.selected_task_ids=[...el('tasks').querySelectorAll('input:checked')].map(x=>x.value);plan=await request('replan',{diagnosis:JSON.parse(el('diagnosis').value),plan,settings,expected_plan_version:plan.plan_version});show();});
handle('export',()=>{if(!plan)throw Error('请先生成计划');const u=URL.createObjectURL(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='action-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
el('demo').onclick=()=>{const d=new Date(Date.now()+86400000).toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});el('deadline').value=d;el('diagnosis').value=JSON.stringify({diagnosis_version:1,mode:'demo',sources:[{source_id:'demo-source',kind:'demo_fixture'}],member_profiles:[{member_id:'B',verified_capabilities:['编写说明']}],gaps:[{gap_id:'G1',target_result:'可复现的启动说明与试用记录',related_member_ids:['B'],required_capabilities:['编写说明'],source_refs:['demo-source'],acceptance_criteria:['另一名成员按说明启动并记录结果'],estimate_minutes_range:[30,60]}]},null,2);el('settings').value=JSON.stringify({member_id:'B',period_start:d,period_end:d,windows:[{date:d,start:'19:00',end:'20:30'}],busy:[],full_dates:[],daily_limit:90,buffer_minutes:10,chunk_minutes:30,allow_split:true},null,2);el('notice').textContent='演示数据，不是实际比赛要求。';};
