'use strict';
const el=id=>document.getElementById(id),key='shanganya-b-draft-v2';let plan=null,diagnosis=null,history=[],availability={},selected=new Set();
const text=(tag,value)=>{const x=document.createElement(tag);x.textContent=value;return x;};
const isoTomorrow=()=>{const d=new Date(Date.now()+86400000);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);};
async function request(path,data){const r=await fetch('/api/agent/planner/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw Error(out.error);return out;}
function snapshot(){return {plan,diagnosis,availability,deadline:el('deadline').value,period_start:el('periodStart').value,period_end:el('periodEnd').value,chunk:+el('chunk').value,split:el('split').checked,selected:[...selected]};}
function save(){localStorage.setItem(key,JSON.stringify(snapshot()));}
function checkpoint(){history.push(JSON.parse(JSON.stringify(snapshot())));if(history.length>10)history.shift();}
function restore(s){plan=s.plan;diagnosis=s.diagnosis;availability=s.availability||{};selected=new Set(s.selected||[]);el('diagnosis').value=JSON.stringify(diagnosis,null,2);el('deadline').value=s.deadline||'';el('periodStart').value=s.period_start||isoTomorrow();el('periodEnd').value=s.period_end||isoTomorrow();el('chunk').value=s.chunk||30;el('split').checked=s.split!==false;show();showAvailability();}
async function perform(fn){document.querySelectorAll('button').forEach(x=>x.disabled=true);try{await fn();save();el('notice').textContent='草案已更新并保存在当前浏览器。请核对风险，再导出给队长采用。';}catch(e){el('notice').textContent=e.message;}finally{document.querySelectorAll('button').forEach(x=>x.disabled=false);}}
function button(label,fn){const x=text('button',label);x.onclick=()=>perform(fn);return x;}
function field(parent,label,value,type='text'){const wrap=document.createElement('label');wrap.append(text('span',label+' '));const x=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')x.type=type;x.value=value;wrap.append(x);parent.append(wrap);return x;}
function common(){if(!plan)throw Error('请先生成任务');return {plan,diagnosis,expected_plan_version:plan.plan_version};}
function show(){el('tasks').replaceChildren();el('paths').replaceChildren();if(!plan){el('progressText').textContent='还没有计划';el('progress').value=0;el('calendar').replaceChildren();el('summary').textContent='尚未生成';el('risks').replaceChildren();el('changes').replaceChildren();el('result').textContent='尚未生成';return;}const counts=plan.tasks.filter(t=>t.status==='completed').length;el('progress').max=Math.max(1,plan.tasks.length);el('progress').value=counts;el('progressText').textContent=`${diagnosis.mode==='demo'?'演示 · ':''}已验收 ${counts} / ${plan.tasks.length} 项 · 待验收 ${plan.tasks.filter(t=>t.status==='pending_review').length} 项 · 草案版本 ${plan.plan_version}`;
for(const path of plan.learning_paths){el('paths').append(text('p',`${path.member_id} · ${path.capability}：必要学习 → 小练习 → 当前作品（${path.gap_id}）`));for(const r of path.resources||[])el('paths').append(text('p','参考资料：'+(r.title||r.url||JSON.stringify(r))));}
const states={candidate:'待选',scheduled:'已安排',in_progress:'进行中',blocked:'阻塞',pending_review:'待验收',completed:'已验收'};
for(const t of plan.tasks){const card=document.createElement('article'),label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.value=t.task_id;check.checked=selected.has(t.task_id);check.disabled=['completed','pending_review'].includes(t.status);check.onchange=()=>{check.checked?selected.add(t.task_id):selected.delete(t.task_id);save();};label.append(check,document.createTextNode(t.title+' · '+states[t.status]));card.append(label);card.append(text('p',`负责人：${t.owner_ids.join('、')} · ${t.estimate_minutes_range.join('–')} 分钟`));card.append(text('p','产物：'+t.deliverable));card.append(text('p','验收：'+t.acceptance_criteria.join('；')));card.append(text('p','步骤：'+t.steps.join(' → ')));card.append(text('p','前置：'+(t.depends_on.join('、')||'无')+' · 来源：'+t.source_refs.join('、')));
const details=document.createElement('details');details.append(text('summary','编辑任务定义'));const title=field(details,'标题',t.title),owners=field(details,'负责人（逗号分隔）',t.owner_ids.join(',')),deliver=field(details,'产物',t.deliverable),criteria=field(details,'验收标准（每行一条）',t.acceptance_criteria.join('\n'),'textarea'),steps=field(details,'步骤（每行一条）',t.steps.join('\n'),'textarea'),lo=field(details,'估时下限',t.estimate_minutes_range[0],'number'),hi=field(details,'估时上限',t.estimate_minutes_range[1],'number'),due=field(details,'截止日期',t.deadline),deps=field(details,'前置任务编号（逗号分隔）',t.depends_on.join(','));details.append(button('保存任务修改',async()=>{const patch={title:title.value,owner_ids:owners.value.split(',').map(x=>x.trim()).filter(Boolean),deliverable:deliver.value,acceptance_criteria:criteria.value.split('\n').filter(Boolean),steps:steps.value.split('\n').filter(Boolean),estimate_minutes_range:[+lo.value,+hi.value],deadline:due.value,depends_on:deps.value.split(',').map(x=>x.trim()).filter(Boolean)};const result=await request('edit',{...common(),task_id:t.task_id,patch});checkpoint();plan=result;show();}));card.append(details);
const feedback=document.createElement('details');feedback.append(text('summary','更新实际用时'));const actual=field(feedback,'累计实际分钟',t.actual_minutes||0,'number'),remaining=field(feedback,'预计剩余分钟',t.remaining_minutes??t.estimate_minutes_range[1],'number');feedback.append(button('记录用时',async()=>{const result=await request('feedback',{...common(),task_id:t.task_id,actual_minutes:+actual.value,remaining_minutes:+remaining.value});checkpoint();plan=result;show();}));feedback.append(text('p','剩余为 0 只进入待验收；正式验收由队长确认。'));card.append(feedback);el('tasks').append(card);}
el('result').textContent=JSON.stringify(plan,null,2);el('calendar').replaceChildren();for(const b of plan.time_blocks){const row=document.createElement('tr');[b.task_id,b.member_id,b.start,b.end,b.locked?'锁定':'普通'].forEach(v=>row.append(text('td',v)));el('calendar').append(row);}const sum=plan.schedule_summary;el('summary').textContent=sum?(sum.fits?'所选可执行任务已排入。':'仍有 '+sum.unallocated_minutes+' 分钟未排入。'):'请先选择任务并预览日程。';el('risks').replaceChildren(...plan.unscheduled.map(x=>text('p',typeof x==='string'?x:`${x.task_id||x.gap_id}：${x.reason}${x.minutes?'（'+x.minutes+' 分钟）':''}`)));for(const f of plan.milestone_forecast||[])el('risks').append(text('p',`条件性倒推 ${f.task_id}：最迟开始 ${f.latest_start||'容量不足'}，尚缺 ${f.missing_minutes} 分钟（依赖及时验收，不等于今日可执行）`));for(const option of sum?.options||[])el('risks').append(text('p','可选调整：'+option));el('changes').replaceChildren(...(plan.changes||[]).map(x=>text('p',x.task_id+'：'+x.reason)));}
function showAvailability(){el('availability').replaceChildren();for(const m of diagnosis?.member_profiles||[]){const who=m.member_id;availability[who]??={daily_limit:90,buffer_minutes:10,windows:[],busy:[],full_dates:[]};const data=availability[who],card=document.createElement('article');card.append(text('h3',who));const limit=field(card,'每日上限（疲劳时可减少）',data.daily_limit,'number'),buffer=field(card,'每日缓冲',data.buffer_minutes,'number');limit.onchange=()=>{data.daily_limit=+limit.value;save();};buffer.onchange=()=>{data.buffer_minutes=+buffer.value;save();};const row=document.createElement('div');row.className='row';const date=field(row,'日期',el('periodStart').value||isoTomorrow(),'date'),start=field(row,'开始','19:00','time'),end=field(row,'结束','20:30','time');row.append(button('添加空闲',()=>{data.windows.push({date:date.value,start:start.value,end:end.value});showAvailability();}),button('添加临时占用',()=>{data.busy.push({date:date.value,start:start.value,end:end.value});showAvailability();}),button('当天排满',()=>{if(!data.full_dates.includes(date.value))data.full_dates.push(date.value);showAvailability();}));card.append(row);for(const type of ['windows','busy','full_dates'])for(const [i,v]of data[type].entries()){const line=text('p',(type==='windows'?'空闲：':type==='busy'?'占用：':'排满：')+(typeof v==='string'?v:`${v.date} ${v.start}–${v.end}`));line.append(button('移除',()=>{data[type].splice(i,1);showAvailability();}));card.append(line);}el('availability').append(card);}}
el('generate').onclick=()=>perform(async()=>{const d=JSON.parse(el('diagnosis').value);const result=await request('generate',{diagnosis:d,context:{deadline:el('deadline').value||'待成员确认'}});checkpoint();diagnosis=d;plan=result;selected.clear();show();showAvailability();});
el('manual').onclick=()=>perform(()=>{checkpoint();const people=el('memberNames').value.split(',').map(x=>x.trim()).filter(Boolean);if(!people.length||!el('source').value.trim())throw Error('请填写成员和来源依据');diagnosis={diagnosis_version:(diagnosis?.diagnosis_version||0)+1,mode:'manual',sources:[{source_id:'manual-source',description:el('source').value,verification_status:'user_provided'}],member_profiles:people.map(member_id=>({member_id,verified_capabilities:[]})),gaps:[{gap_id:'G1',target_result:el('target').value,source_refs:['manual-source'],related_member_ids:people,required_capabilities:el('skills').value.split(',').map(x=>x.trim()).filter(Boolean),acceptance_criteria:el('criteria').value.split('\n').filter(Boolean)}]};el('diagnosis').value=JSON.stringify(diagnosis,null,2);plan=null;selected.clear();el('tasks').replaceChildren();showAvailability();});
el('schedule').onclick=()=>perform(async()=>{const settings={members:availability,period_start:el('periodStart').value,period_end:el('periodEnd').value,selected_task_ids:[...selected],chunk_minutes:+el('chunk').value,allow_split:el('split').checked};const result=await request('replan',{...common(),settings});checkpoint();plan=result;show();});
el('export').onclick=()=>perform(()=>{common();const u=URL.createObjectURL(new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='B-action-plan-bundle.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
el('undo').onclick=()=>perform(async()=>{if(!history.length)throw Error('本次打开页面尚无可撤销操作');const s=history[history.length-1];if(s.plan)await request('validate',{plan:s.plan,diagnosis:s.diagnosis});history.pop();restore(s);});
el('import').onchange=()=>perform(async()=>{const file=el('import').files[0];if(!file)return;if(file.size>4000000)throw Error('文件不得超过 4 MB');const value=JSON.parse(await file.text());if(value.plan){await request('validate',value);checkpoint();restore(value);}else{if(!Array.isArray(value.gaps)||!Array.isArray(value.member_profiles))throw Error('请选择 A 诊断或 B 交接包');checkpoint();diagnosis=value;plan=null;selected.clear();el('diagnosis').value=JSON.stringify(value,null,2);el('tasks').replaceChildren();showAvailability();}});
el('demo').onclick=()=>perform(()=>{checkpoint();const d=isoTomorrow();restore({deadline:d,period_start:d,period_end:d,diagnosis:{diagnosis_version:1,mode:'demo',sources:[{source_id:'demo-source',kind:'demo_fixture'}],member_profiles:[{member_id:'B',verified_capabilities:['编写说明']},{member_id:'C',verified_capabilities:['编写说明']}],gaps:[{gap_id:'G1',target_result:'可复现的启动说明与试用记录',related_member_ids:['B','C'],required_capabilities:['编写说明'],source_refs:['demo-source'],acceptance_criteria:['另一名成员按说明启动并记录结果'],estimate_minutes_range:[30,60]}]},plan:null,availability:{B:{daily_limit:90,buffer_minutes:10,windows:[{date:d,start:'19:00',end:'20:30'}],busy:[],full_dates:[]},C:{daily_limit:90,buffer_minutes:10,windows:[{date:d,start:'19:30',end:'21:00'}],busy:[],full_dates:[]}}});el('notice').textContent='演示数据';});
for(const id of ['periodStart','periodEnd','chunk','split','deadline'])el(id).addEventListener('change',save);
(async()=>{try{const raw=localStorage.getItem(key);if(raw){const s=JSON.parse(raw);if(s.plan)await request('validate',{plan:s.plan,diagnosis:s.diagnosis});restore(s);el('notice').textContent='已恢复本浏览器的草案；这不是队长正式采纳记录。';}else{el('periodStart').value=el('periodEnd').value=isoTomorrow();}}catch(e){el('notice').textContent='草案恢复失败：'+e.message;}})();
