const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'team-check-'));let server,browser;const errors=[];const base='http://127.0.0.1:8924';
(async()=>{try{
server=spawn('python',['learning_agent_server.py','--port','8924'],{cwd:__dirname,env:{...process.env,SHANGAN_AGENT_DATA:temp},stdio:'ignore'});
for(let i=0;i<40;i++){try{if((await fetch(base+'/api/agent/team')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/team.html');await page.locator('#goal').fill('浏览器测试：队长总控交接');await page.locator('#create button').click();await page.locator('#demo:visible').waitFor();await page.locator('#demo').click();await page.locator('#apply:enabled').waitFor();assert.equal(await page.locator('#tasks .task').count(),0);await page.locator('#apply').click();await page.getByRole('button',{name:'开始任务',exact:true}).click();await page.locator('#note').fill('开始检查');await page.locator('#feedback-form button[type=submit]').click();await page.getByRole('button',{name:'提交成果',exact:true}).click();await page.locator('#note').fill('提交试用记录');await page.locator('#evidence').fill('Demo：已跑通页面到API的流程');await page.locator('#feedback-form button[type=submit]').click();await page.getByRole('button',{name:'验收通过',exact:true}).waitFor();
await page.reload();await page.getByRole('button',{name:'验收通过',exact:true}).click();await page.locator('#note').fill('A 核对示例记录后通过');await page.locator('#reviewer').selectOption('A');await page.locator('#feedback-form button[type=submit]').click();await page.getByRole('heading',{name:'验证一次三人交接 · 已验收',exact:true}).waitFor();
const state=await(await fetch(base+'/api/agent/team')).json();assert.equal(state.projects[0].plan.tasks[0].status,'completed');assert.equal(state.projects[0].feedback.length,3);assert.equal(state.projects[0].feedback[2].reviewer_id,'A');
fs.mkdirSync(path.join(__dirname,'test-output'),{recursive:true});await page.screenshot({path:path.join(__dirname,'test-output/team-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,browserErrors:errors,checks:['create','A-to-B-demo','preview-before-apply','start','submit-pending-review','reload-persistence','review-with-evidence','API-state','mobile-no-overflow']}));
}finally{if(browser)await browser.close();if(server){const done=new Promise(r=>server.once('exit',r));server.kill();await done;}fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1});
