const {spawn}=require('node:child_process'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
const base='http://127.0.0.1:8934';let server,browser;
(async()=>{try{server=spawn('python',['learning_agent_server.py','--port','8934'],{cwd:__dirname,stdio:'ignore'});for(let i=0;i<50;i++){try{if((await fetch(base+'/api/agent/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1360,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/planner.html');await page.getByRole('button',{name:'载入演示',exact:true}).click();await page.getByRole('button',{name:'生成个人任务路线'}).click();await page.locator('#tasks article').waitFor();assert.equal(await page.locator('#tasks article').count(),1);await page.locator('#tasks input[type=checkbox]').check();await page.getByRole('button',{name:'预览排程 / 局部重排'}).click();await page.waitForFunction(()=>document.querySelector('#calendar').children.length>0);assert.equal(await page.locator('#calendar tr').count(),4);await page.reload();await page.waitForFunction(()=>document.querySelector('#calendar').children.length===4);assert.match(await page.locator('#notice').textContent(),/已恢复/);
await page.getByText('编辑任务定义',{exact:true}).click();await page.getByLabel('标题',{exact:true}).fill('修改后的交付说明');await page.getByRole('button',{name:'保存任务修改'}).click();await page.waitForFunction(()=>document.querySelector('#calendar').children.length===0);assert.match(await page.locator('#tasks').textContent(),/修改后的交付说明/);await page.getByRole('button',{name:'撤销上次草案修改'}).click();await page.waitForFunction(()=>document.querySelector('#calendar').children.length===4);
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'导出交接包'}).click();const download=await downloadPromise;const file=await download.path();await Promise.all([page.waitForResponse(r=>r.url().endsWith('/planner/validate')),page.locator('#import').setInputFiles(file)]);await page.waitForFunction(()=>!document.querySelector('#schedule').disabled);
// Capacity and unexpected-event checks use actual form controls and server responses.
const bcard=page.locator('#availability article').first();
await bcard.getByLabel('每日上限（疲劳时可减少）').fill('30');await bcard.getByLabel('每日缓冲',{exact:true}).fill('0');await page.locator('#chunk').click();
await page.getByRole('button',{name:'预览排程 / 局部重排'}).click();await page.waitForFunction(()=>!document.querySelector('#schedule').disabled);assert.match(await page.locator('#summary').textContent(),/30 分钟未排入/);
await bcard.getByLabel('每日上限（疲劳时可减少）').fill('90');await bcard.getByLabel('开始',{exact:true}).fill('19:30');await bcard.getByLabel('结束',{exact:true}).fill('20:00');await bcard.getByRole('button',{name:'添加临时占用'}).click();
await page.getByRole('button',{name:'预览排程 / 局部重排'}).click();await page.waitForFunction(()=>!document.querySelector('#schedule').disabled && document.querySelector('#calendar tr td:nth-child(3)')?.textContent.includes('T20:00'));
assert.equal(await page.locator('#calendar tr').count(),2);assert.match(await page.locator('#risks').textContent(),/30 分钟/);
// Invalid imports must not destroy the current draft.
const before=await page.locator('#result').textContent();const invalid=JSON.parse(require('node:fs').readFileSync(file,'utf8'));invalid.plan.tasks[0].source_refs=[];
await page.locator('#import').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('任务关联无效'));assert.equal(await page.locator('#result').textContent(),before);
await page.locator('#import').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('#calendar').children.length===4);
await page.getByText('更新实际用时',{exact:true}).click();await page.getByLabel('累计实际分钟').fill('70');await page.getByLabel('预计剩余分钟').fill('0');await page.getByRole('button',{name:'记录用时',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#progressText').textContent.includes('待验收 1'));assert.equal(await page.locator('#progress').getAttribute('value'),'0');assert.doesNotMatch(await page.locator('#risks').textContent(),/条件性倒推/);
await page.screenshot({path:path.join(__dirname,'test-output/planner-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'test-output/planner-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);assert.deepEqual(errors,[]);
// Starting a new manual diagnosis must clear all old progress and calendars.
await page.locator('#target').fill('新的作品');await page.locator('#criteria').fill('可复现');await page.locator('#source').fill('用户材料');await page.getByRole('button',{name:'用以上内容建立手工诊断'}).click();await page.waitForFunction(()=>document.querySelector('#tasks').children.length===0);assert.equal(await page.locator('#progressText').textContent(),'还没有计划');console.log('PASS: shared schedule; refresh restore; edit invalidation; undo; export/import; capacity shortage; interruption replan; invalid import preserves draft; pending-review feedback; desktop/mobile layout; new diagnosis clears progress; no JS errors');}finally{if(browser)await browser.close();if(server)server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
