const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'period-check-'));let server,browser;const errors=[];const base='http://127.0.0.1:8925';
async function post(route,data){const r=await fetch(base+'/api/agent/team/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await r.json();assert.equal(r.status,200,JSON.stringify(value));return value;}
(async()=>{try{
server=spawn('python',['learning_agent_server.py','--port','8925'],{cwd:__dirname,env:{...process.env,SHANGAN_AGENT_DATA:temp},stdio:'ignore'});
for(let i=0;i<40;i++){try{if((await fetch(base+'/api/agent/team')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
let p=await post('create',{goal:'测试夹具：今天满了，周期内安排并应对临时会议',mode:'demo'});
const ctx=()=>({project_id:p.project_id,expected_version:p.version});p=await post('demo',ctx());p=await post('apply',{...ctx(),proposal_id:p.proposal.id});
const plan=structuredClone(p.plan);plan.plan_version++;plan.tasks[0].estimate_minutes_range=[90,120];p=await post('propose',{...ctx(),plan,reason:'测试夹具：剩余任务120分钟'});p=await post('apply',{...ctx(),proposal_id:p.proposal.id});
browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1100}});page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/team.html');await page.locator('#period-panel:visible').waitFor();await page.locator('#refresh').click();await page.getByText('已读取后端最新状态',{exact:true}).waitFor();
const today=await page.locator('#period-start').inputValue();const plus=n=>{const d=new Date(today+'T00:00:00+08:00');d.setUTCDate(d.getUTCDate()+n);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);};const d1=plus(1),d2=plus(2);
await page.locator('#period-end').fill(d2);await page.locator('#period-windows').fill(`${today} 19:00 20:00\n${d1} 19:00 20:00\n${d2} 19:00 20:00`);await page.locator('#period-buffer').fill('0');await page.locator('#allow-split').check();await page.locator('#today-full').click();await page.locator('.period-choice').check();await page.locator('#period-reason').fill('今天其他任务已满');await page.locator('#period-preview').click();await page.locator('#apply-period:enabled').waitFor();await page.getByText('本轮待安排 120 分钟 / 可用 120 分钟 / 未排入 0 分钟',{exact:true}).waitFor();
let state=await(await fetch(base+'/api/agent/team?id='+p.project_id)).json();assert.equal(state.plan.time_blocks.length,0);assert.ok(state.proposal.plan.time_blocks.every(x=>x.start.slice(0,10)!==today));await page.locator('#apply-period').click();await page.getByRole('heading',{name:'已采用的周期安排',exact:true}).waitFor();const first=await(await fetch(base+'/api/agent/team?id='+p.project_id)).json();await page.reload();await page.getByRole('heading',{name:'已采用的周期安排',exact:true}).waitFor();
await page.locator('#period-busy').fill(`${d1} 19:00 19:30`);await page.locator('#period-reason').fill('临时开会占用30分钟');await page.locator('#period-preview').click();await page.locator('#apply-period:enabled').waitFor();await page.getByText('本轮待安排 120 分钟 / 可用 90 分钟 / 未排入 30 分钟',{exact:true}).waitFor();await page.locator('#apply-period').click();await page.getByRole('heading',{name:'已采用的周期安排',exact:true}).waitFor();await page.locator('#undo-period:enabled').click();await page.getByText('本轮待安排 120 分钟 / 可用 120 分钟 / 未排入 0 分钟',{exact:true}).waitFor();state=await(await fetch(base+'/api/agent/team?id='+p.project_id)).json();assert.deepEqual(state.plan.time_blocks,first.plan.time_blocks);assert.ok(state.version>first.version);
fs.mkdirSync(path.join(__dirname,'test-output'),{recursive:true});await page.locator('#period-panel').screenshot({path:path.join(__dirname,'test-output/period-desktop.png')});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
console.log(JSON.stringify({ok:true,checks:['today-full-skipped','whole-period-capacity','preview-does-not-apply','apply-and-reload','unexpected-event-subtracted','30-minute-gap-visible','undo-restores-before-schedule','version-retained','mobile-no-overflow'],browserErrors:errors}));
}finally{if(browser)await browser.close();if(server){const done=new Promise(r=>server.once('exit',r));server.kill();await done;}fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1});
