const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'dispatch-check-'));let server,browser;const errors=[];const base='http://127.0.0.1:8926';
async function post(route,data){const r=await fetch(base+'/api/agent/team/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await r.json();assert.equal(r.status,200,JSON.stringify(value));return value;}
(async()=>{try{
server=spawn('python',['learning_agent_server.py','--port','8926'],{cwd:__dirname,env:{...process.env,SHANGAN_AGENT_DATA:temp},stdio:'ignore'});
for(let i=0;i<40;i++){try{if((await fetch(base+'/api/agent/team')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
let p=await post('create',{goal:'总调度浏览器测试夹具',mode:'demo'});
browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1365,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/team.html');await page.locator('#dispatch-run:enabled').waitFor();await page.locator('#dispatch-run').click();await page.getByText('计划已生成，请核对后采用',{exact:true}).waitFor();
let saved=await(await fetch(base+'/api/agent/team?id='+p.project_id)).json();assert.equal(saved.dispatch.status,'succeeded');assert.equal(saved.plan,null);assert.equal(saved.dispatch_status.stage,'confirm');await page.locator('#apply').click();await page.locator('#period-panel:visible').waitFor();await page.reload();await page.getByText('按已采用计划推进，变化时预览调整',{exact:true}).waitFor();
await page.getByText('补充目标、截止、能力或材料信息',{exact:true}).click();await page.locator('#brief-content').fill('新增要求：提供操作步骤与成果截图');await page.locator('#brief-form button').click();await page.getByText('等待 A 诊断最新目标与材料',{exact:true}).waitFor();saved=await(await fetch(base+'/api/agent/team?id='+p.project_id)).json();assert.equal(saved.plan_stale,true);assert.equal(saved.brief_history.length,1);
await page.locator('#dispatch-run').click();await page.getByText('计划已生成，请核对后采用',{exact:true}).waitFor();saved=await(await fetch(base+'/api/agent/team?id='+p.project_id)).json();assert.equal(saved.diagnosis.diagnosis_version,2);assert.ok(saved.proposal);assert.equal(saved.plan.plan_version,1);
fs.mkdirSync(path.join(__dirname,'test-output'),{recursive:true});await page.screenshot({path:path.join(__dirname,'test-output/dispatch-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
const live=await post('create',{goal:'真实项目缺少适配器的测试夹具',mode:'live'});await page.reload();await page.locator('#projects').selectOption(live.project_id);await page.getByText('A：待接入 / B：待接入',{exact:true}).waitFor();assert.equal(await page.locator('#dispatch-run').isDisabled(),true);assert.deepEqual(errors,[]);
console.log(JSON.stringify({ok:true,checks:['dispatch-to-preview','confirmation-required','adopt-and-reload','brief-invalidates-old-plan','rediagnosis-version','live-not-simulated','mobile-no-overflow'],browserErrors:errors}));
}finally{if(browser)await browser.close();if(server){const done=new Promise(r=>server.once('exit',r));server.kill();await done;}fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1});
