const {spawn}=require('node:child_process'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
const base='http://127.0.0.1:8934';let server,browser;
(async()=>{try{server=spawn('python',['learning_agent_server.py','--port','8934'],{cwd:__dirname,stdio:'ignore'});for(let i=0;i<50;i++){try{if((await fetch(base+'/api/agent/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1360,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/planner.html');await page.getByRole('button',{name:'载入演示',exact:true}).click();await page.getByRole('button',{name:'生成个人任务路线'}).click();await page.locator('#tasks article').waitFor();assert.equal(await page.locator('#tasks article').count(),1);await page.locator('#tasks input[type=checkbox]').check();await page.getByRole('button',{name:'预览排程 / 局部重排'}).click();await page.waitForFunction(()=>document.querySelector('#calendar').children.length>0);assert.equal(await page.locator('#calendar tr').count(),4);await page.reload();await page.waitForFunction(()=>document.querySelector('#calendar').children.length===4);assert.match(await page.locator('#notice').textContent(),/已恢复/);
await page.getByText('编辑任务定义',{exact:true}).click();await page.getByLabel('标题',{exact:true}).fill('修改后的交付说明');await page.getByRole('button',{name:'保存任务修改'}).click();await page.waitForFunction(()=>document.querySelector('#calendar').children.length===0);assert.match(await page.locator('#tasks').textContent(),/修改后的交付说明/);await page.getByRole('button',{name:'撤销上次草案修改'}).click();await page.waitForFunction(()=>document.querySelector('#calendar').children.length===4);
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'导出交接包'}).click();const download=await downloadPromise;const file=await download.path();await page.locator('#import').setInputFiles(file);await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('草案已更新'));
await page.getByText('更新实际用时',{exact:true}).click();await page.getByLabel('累计实际分钟').fill('70');await page.getByLabel('预计剩余分钟').fill('0');await page.getByRole('button',{name:'记录用时',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#progressText').textContent.includes('待验收 1'));assert.equal(await page.locator('#progress').getAttribute('value'),'0');
await page.screenshot({path:path.join(__dirname,'test-output/planner-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS: shared schedule, refresh restore, edit invalidation, undo, export/import, feedback pending-review, mobile width, no JS errors');}finally{if(browser)await browser.close();if(server)server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
